name: s_future_button
description: A Future Button widget with full async operation support, which Handles loading, success, error, and reset states.
issue_tracker: https://github.com/SoundSliced/s_future_button/issues
repository: https://github.com/SoundSliced/s_future_button
version: 2.1.0
homepage: https://github.com/SoundSliced/s_future_button

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_packages: ^1.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fake_async: ^1.3.1

flutter:
  uses-material-design: true